---
- name: this playbook creates a file or directory
  hosts: webservers

  tasks:
    - name: creating a directory
      file: 
        path: /home/ansible/school
        state: directory
    - name: creating a file
      file: 
        path: /home/ansible/dir1/firstgrade.txt
        state: touch
